highlight:
  noClasses: false
goldmark:
  extensions:
    cjk:
      eastAsianLineBreaks: true
      eastAsianLineBreaksStyle: simple
      enable: true
      escapedSpace: true
  parser:
    wrapStandAloneImageWithinParagraph: false
