hugoVersion:
  extended: false
  min: "0.123.0"
mounts:
  - source: assets
    target: assets
  - source: hugo_stats\.json
    target: assets/watching/hugo_stats\.json
imports:
  - path: github.com/HuaDeity/hugo-multipaper
workspace: "hugo.work"
